pipeline:
  docker:
    image: plugins/docker
    repo: jonnrb/hostapd_grpc
    storage_driver: overlay2
    secrets: [ docker_username, docker_password ]

  trigger:
    image: plugins/downstream
    server: https://drone.jonnrb.com
    fork: true
    repositories:
      - jon/wifi_dash
    secrets: [ downstream_token ]

