load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
    name = "cc_api",
    protos = ["api.proto"],
    visibility = ["//visibility:public"],
    with_grpc = True,
)
